name: Retire.js Security Scan

on:
  push:
    branches:
      - main 

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the desired Node.js version

      - name: Install Dependencies
        run: npm install  # You may need to adjust this if your project uses a different package manager

      - name: Run Retire.js Security Scan
        run: npx retire

